### ISSUE TITLE
CORS error :Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by Gabriel0402** [MartinYehPSU/CoilBackend#12]
There is an backend error when post or get with authorization. I got Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.

This is an API issue, you won't get this error if using Postman/Fielder to send HTTP requests to API. In case of browsers, for security purpose, they always send OPTIONS request/preflight to API before sending the actual requests (GET/POST/PUT/DELETE). Therefore, in case, the request method is OPTION, not only you need to add "Authorization" into "Access-Control-Allow-Headers", but you need to add "OPTIONS" into "Access-Control-allow-methods" as well.

**Comment by MartinYehPSU** [comment]
Which API gave you this error? POST /auth/login?

**Comment by Gabriel0402** [comment]
Thanks, your help is appreciated. The post request for authentication works. However all the other calls did not work. It failed at the option request level. I’ve committed my code to the GitHub. You may want to check it out. Did your endpoint try some other data calls such as GET accounts from localhost or 127.0.0.1? I assume this is the CORS issue I met before. Thanks for your help.

**Comment by MartinYehPSU** [comment]
@Gabriel0402 reported this issue is fixed.
