### ISSUE TITLE
delay in jwt token validation

### ISSUE THREAD

**Issue by Gabriel0402** [MartinYehPSU/CoilBackend#17]
It seems there's a delay for jwt token validation. When I login, the rest call has a 200 return with a invalid JWT token. However when make this call 1 second later with the same jwt token it's working. Is there any delay in jwt token validation?

**Comment by MartinYehPSU** [comment]
I've made some small adjustments in generating JWT and when it can be used/expired. Please try again.

**Comment by Gabriel0402** [comment]
it works, thanks
