### ISSUE TITLE
chat API is not working

### ISSUE THREAD

**Issue by Gabriel0402** [MartinYehPSU/CoilBackend#23]
The chat API is not working. For example, when I use account 1 to sent message to account 2, the post request shows chat sent. However I'm using get chat request from uesrId 1 and an empty array returns.

**Comment by MartinYehPSU** [comment]
Oh if u r log in as user 1 then u should request for the chats between u
and another user, such as 2. Chat between 1 and 1 is empty.

**Comment by MartinYehPSU** [comment]
I will change the API to be:
GET /chats/{userId1}/{userId2}
for chats between user 1 and user 2. I will let you know when this is done.

**Comment by Gabriel0402** [comment]
Thanks, this makes more sense.
